config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes  do
    collection do
      get 'search'
    end
  end

  root 'recipes#index'

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_many :recipes
end

app/models/food_preference.rb
class FoodPreference < ActiveRecord::Base
  has_many :recipes
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  DIFFICULTY=%w(Easy Medium Hard)
  belongs_to :food_type
  belongs_to :food_preference
  belongs_to :cuisine

  def self.search(search)
    fp = FoodPreference.find_by_name(search)
    ft = FoodType.find_by_name(search)
    cuisine = Cuisine.find_by_name(search)
    fp.nil? ? ft.nil? ? cuisine.nil? ? a = 0 : a = cuisine : a = ft : a= fp
    if !fp.nil?
      Recipe.where("food_preference_id = ?", fp.id)
    elsif !ft.nil?
      Recipe.where("food_type_id = ?", ft.id)
    else
      Recipe.where("cuisine_id = ?", cuisine.id)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :create,:update, :destroy]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
     @search_results = Recipe.search(params["search"])
    respond_to do |format|
      format.js # search.js.erb
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :cooking_time, :difficulty_level, :food_type_id, :food_preference_id, :cuisine_id, :ingredients, :procedure)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def all_food_type
    food_types = FoodType.all
  end
  def all_food_preference
    food_preferences = FoodPreference.all
  end
  def all_cuisine
    cuisines = Cuisine.all
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CurryNation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
   <div class="navbar navbar-static-top">
        <a class="navbar-brand" href="/recipes"><%= image_tag "currynation.jpg", :size => "70x50"%></a>
     <div class="nav-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Recipes",recipes_path %></li>
        </ul>
         <ul class="nav navbar-nav pull-right">
             <% if user_signed_in? %>
                 <li><%=link_to "#{current_user.email}"%></li>
                 <li class="active"><%= link_to "Logout",destroy_user_session_path%></li>
             <%else%>
                 <li><%= link_to "Login", new_user_session_path %></li>
                  <li class="active"><%= link_to "SignUp", new_user_registration_path%></li>
             <%end%>
         </ul>
     </div><!--/.nav-collapse -->
   </div>
  <div class="row">
    <div class="col-lg-2">
      <div class="panel panel-primary" id="panels">
        <div class="panel-heading">Food Preferences
        </div>
        <% all_food_preference.each do |fp| %>
            <p> <%= link_to "#{fp.name}", "/recipes/search?search=#{fp.name}", :class => "dropdown-toggle", :remote => true%></p>
        <%end%>
      </div>
      <div class="panel panel-primary" id="panels">
        <div class="panel-heading">Food Type
        </div>
        <% all_food_type.each do |ft| %>
            <p> <%= link_to "#{ft.name}", "/recipes/search?search=#{ft.name}", :class => "dropdown-toggle",:remote => true %></p>
        <%end%>
      </div>
      <div class="panel panel-primary" id="panels">
        <div class="panel-heading">Cuisine
        </div>
        <% all_cuisine.each do |c| %>
           <p> <%= link_to "#{c.name}", "/recipes/search?search=#{c.name}", :class => "dropdown-toggle",:remote => true %></p>
        <%end%>
      </div>
    </div>
    <div class="col-lg-9">
      <div id="search_result">

      </div>
      <div id="main_block">
         <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :cooking_time %><br>
    <%= f.text_field :cooking_time %>
  </div>
  <div class="field">
    <%= f.label :difficulty_level %><br>
    <%=f.select :difficulty_level, Recipe::DIFFICULTY,{:prompt => 'Please Choose'}, :class => "form-control"%>
  </div>
    <div class="field">
      <%= f.label :food_preference %><br>
      <%= f.select(:food_preference_id,options_from_collection_for_select(FoodPreference.all,:id, :name), {:prompt => 'Please Choose'}, :class => "form-control") %>
    </div>

    <div class="field">
      <%= f.label :food_type %><br>
      <%= f.select(:food_type_id, options_from_collection_for_select(FoodType.all, :id,:name), {:prompt => 'Please Choose'}, :class => "form-control") %>
    </div>
    <div class="field">
      <%= f.label :cuisine %><br>
      <%= f.select(:cuisine_id,options_from_collection_for_select(Cuisine.all, :id,:name), {:prompt => 'Please Choose'}, :class => "form-control") %>
    </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :procedure %><br>
    <%= f.text_area :procedure %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_search_result.html.erb
<h1>Listing Recipes</h1>

<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th>Cooking time</th>
    <th>Difficulty level</th>
    <th>Food type</th>
    <th>Food preference</th>
    <th>Cuisine</th>
    <th>Ingredients</th>
    <th>Procedure</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% search_results.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.cooking_time %></td>
        <td><%= recipe.difficulty_level %></td>
        <td><%= recipe.food_type.name %></td>
        <td><%= recipe.food_preference.name  %></td>
        <td><%= recipe.cuisine.name %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.procedure %></td>
        <td><%= link_to 'Show', recipe , :class =>"btn btn-primary btn-small"%></td>
        <% if user_signed_in? %>
            <td><%= link_to 'Edit', edit_recipe_path(recipe),:class=>"btn btn-success btn-small"%></td>
            <td><%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "btn btn-danger btn-small" %></td>
        <%end%>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Cooking time</th>
      <th>Difficulty level</th>
      <th>Food type</th>
      <th>Food preference</th>
      <th>Cuisine</th>
      <th>Ingredients</th>
      <th>Procedure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.cooking_time %></td>
        <td><%= recipe.difficulty_level %></td>
        <td><%= recipe.food_type.name %></td>
        <td><%= recipe.food_preference.name  %></td>
        <td><%= recipe.cuisine.name %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.procedure %></td>
        <td><%= link_to 'Show', recipe , :class =>"btn btn-primary btn-small"%></td>
        <% if user_signed_in? %>
            <td><%= link_to 'Edit', edit_recipe_path(recipe),:class=>"btn btn-success btn-small"%></td>
            <td><%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "btn btn-danger btn-small" %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/search.js.erb
$("#search_result").css("display", "block");
$("#search_result").html("<%= escape_javascript(render partial: 'search_result', locals: { search_results: @search_results} ) %>");
$("#main_block").css("display", "none");

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= @recipe.cooking_time %>
</p>

<p>
  <strong>Difficulty level:</strong>
  <%= @recipe.difficulty_level %>
</p>

<p>
  <strong>Food type:</strong>
  <%= @recipe.food_type_id %>
</p>

<p>
  <strong>Food preference:</strong>
  <%= @recipe.food_preference_id %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @recipe.cuisine_id %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Procedure:</strong>
  <%= @recipe.procedure %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>